// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGE2ppgytLG_v8K9424P-th2hpl47VE9c',
    appId: '1:948387819949:web:10d9c166eb7af3d554f124',
    messagingSenderId: '948387819949',
    projectId: 'requester-dbd27',
    authDomain: 'requester-dbd27.firebaseapp.com',
    storageBucket: 'requester-dbd27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9OQjdPmn4cIMI3p-hkedmTfDzdElac_A',
    appId: '1:948387819949:android:efe8fb92c69fd70f54f124',
    messagingSenderId: '948387819949',
    projectId: 'requester-dbd27',
    storageBucket: 'requester-dbd27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQvEoVkT7fx9DmiXkp98-bXaHoAQyMPtM',
    appId: '1:948387819949:ios:264fec315524762854f124',
    messagingSenderId: '948387819949',
    projectId: 'requester-dbd27',
    storageBucket: 'requester-dbd27.appspot.com',
    iosBundleId: 'efafi.mostafa.requester',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQvEoVkT7fx9DmiXkp98-bXaHoAQyMPtM',
    appId: '1:948387819949:ios:264fec315524762854f124',
    messagingSenderId: '948387819949',
    projectId: 'requester-dbd27',
    storageBucket: 'requester-dbd27.appspot.com',
    iosBundleId: 'efafi.mostafa.requester',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGE2ppgytLG_v8K9424P-th2hpl47VE9c',
    appId: '1:948387819949:web:a2d16d5caf74745f54f124',
    messagingSenderId: '948387819949',
    projectId: 'requester-dbd27',
    authDomain: 'requester-dbd27.firebaseapp.com',
    storageBucket: 'requester-dbd27.appspot.com',
  );
}
