// Mocks generated by Mockito 5.3.2 from annotations
// in requester/test/features/feature_requester/data/data_source/remote/api_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:requester/core/resource/data_state.dart' as _i2;
import 'package:requester/core/rest/rest_api.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RestApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestApi extends _i1.Mock implements _i3.RestApi {
  MockRestApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<_i5.Response<dynamic>>> request(
    String? url, {
    _i3.RequestType? requestType = _i3.RequestType.getRequest,
    dynamic body,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #requestType: requestType,
            #body: body,
            #headers: headers,
          },
        ),
        returnValue: _i4.Future<_i2.DataState<_i5.Response<dynamic>>>.value(
            _FakeDataState_0<_i5.Response<dynamic>>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #requestType: requestType,
              #body: body,
              #headers: headers,
            },
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i5.Response<dynamic>>>);
  @override
  String makeAlerts({_i5.Response<dynamic>? response}) => (super.noSuchMethod(
        Invocation.method(
          #makeAlerts,
          [],
          {#response: response},
        ),
        returnValue: '',
      ) as String);
}
